### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Robin5577** [Safeheron/safeheron-crypto-suites-cpp#1]
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/7920189/204183545-c1db6575-434d-41e4-a3e4-2e5bfbc95dba.png">

I got an error when compiling，Can you help me？

**Comment by singhparshant** [comment]
What version of protobuf is used to build this ?

**Comment by sword03** [comment]
> What version of protobuf is used to build this ?

Hi, You should use protobuf 3.14 or 3.20, because we only made adaptations for these two versions of protobuf.

**Comment by sword03** [comment]
> <img alt="image" width="1656" src="https://user-images.githubusercontent.com/7920189/204183545-c1db6575-434d-41e4-a3e4-2e5bfbc95dba.png">
> 
> I got an error when compiling，Can you help me？

Update to the latest version and compile it again. I think it would work.
