### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by singhparshant** [Safeheron/safeheron-crypto-suites-cpp#3]
I get the protobuf version mismatch error while running "make" command. Could you let me know which version should I install for ptotobuf. I tried with 3.12 and 3.21

`../safeheron-crypto-suites-cpp/src/crypto-curve-cpp/src/crypto-curve/proto_gen/curve_point.pb.switch.h:17:2: error: Invalid version of protobuf.
#error Invalid version of protobuf.
 ^`

**Comment by sword03** [comment]
@singhparshant Hi, You should use protobuf 3.14 or 3.20,  because we only made adaptations for these two versions of protobuf.

**Comment by mstc-xqp** [comment]
![Screenshot from 2024-01-03 16-50-52](https://github.com/Safeheron/safeheron-crypto-suites-cpp/assets/19384581/9ada73e2-4487-45aa-9f52-eed6e55046cd)
why? my protobuf version is 3.20

**Comment by sword03** [comment]
Hi, it doesn't seem to be a problem with the protobuf version. Note that the header files cannot be found. Have you checked whether the protobuf installation is normal?
